spring:
    application:
      name: gateway-server 
    config:
        import: optional:configserver:http://config-server:8071
    cloud:
        config: 
            uri: http://configserver:8071

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.optimagrowth: DEBUG
            