spring:
    application:
        name: eureka-server 
    config:
        import: optional:configserver:http://config-server:8071
    cloud:
        config: 
            uri: http://configserver:8071
