services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "ostock_dev"
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
        - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  config-server:
    build: 
      context: ..
      dockerfile: services/config-server/Dockerfile
    container_name: config-server
    ports:
      - "8071:8071"
    environment:
      SERVER_PORT: 8071
      SPRING_PROFILES_ACTIVE: native
      SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS: classpath:/config
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:8071/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 20s
    networks:
      backend:
        aliases:
          - "configserver"

  product-service:
    build:
      context: ..
      dockerfile: services/product-service/Dockerfile
    container_name: product-service
    depends_on:
      database:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: product-service
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8071
      SPRING_PROFILES_ACTIVE: dev
      DATABASESERVER_PORT: "5432"
    ports:
      - "8081:8081"
    networks:
      - backend

  planning-service:
    build:
      context: ..
      dockerfile: services/planning-service/Dockerfile
    container_name: planning-service
    depends_on:
      database:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: planning-service
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8071
      SPRING_PROFILES_ACTIVE: dev
      DATABASESERVER_PORT: "5432"
    ports:
      - "8082:8082"
    networks:
      - backend

  execution-service:
    build:
      context: ..
      dockerfile: services/execution-service/Dockerfile
    container_name: execution-service
    depends_on:
      database:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: execution-service
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8071
      SPRING_PROFILES_ACTIVE: dev
      DATABASESERVER_PORT: "5432"
    ports:
      - "8083:8083"
    networks:
      - backend
networks:
  backend: 

