services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "ostock_dev"
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
        - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  config-server:
    build: 
      context: ..
      dockerfile: services/config-server/Dockerfile        # your config-server Dockerfile
    container_name: config-server
    ports:
      - "8071:8071"
    environment:
      SERVER_PORT: 8071
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:8071/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 20s
    networks:
      backend:
        aliases:
          - "configserver"

  product-service:
    build:
      context: ..
      dockerfile: services/product-service/Dockerfile
    container_name: product-service
    depends_on:
      database:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/ostock_dev
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: "true"
      SPRING_SQL_INIT_MODE: always
      SPRING_CLOUD_CONFIG_ENABLED: "false"
      SERVER_PORT: 8081
      CONFIGSERVER_URI: "http://configserver:8071"
      CONFIGSERVER_PORT:   "8071"
      DATABASESERVER_PORT: "5432"
    ports:
      - "8081:8081"
    networks:
      - backend

  planning-service:
    build:
      context: ..
      dockerfile: services/planning-service/Dockerfile
    container_name: planning-service
    depends_on:
      database:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/ostock_dev
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: "true"
      SPRING_SQL_INIT_MODE: always
      SPRING_CLOUD_CONFIG_ENABLED: "false"
      SERVER_PORT: 8082
      CONFIGSERVER_URI: "http://configserver:8071"
      CONFIGSERVER_PORT:   "8071"
      DATABASESERVER_PORT: "5432"
    ports:
      - "8082:8082"
    networks:
      - backend

  execution-service:
    build:
      context: ..
      dockerfile: services/execution-service/Dockerfile
    container_name: execution-service
    depends_on:
      database:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/ostock_dev
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: "true"
      SPRING_SQL_INIT_MODE: always
      SPRING_CLOUD_CONFIG_ENABLED: "false"
      SERVER_PORT: 8082
      CONFIGSERVER_URI: "http://configserver:8071"
      CONFIGSERVER_PORT:   "8071"
      DATABASESERVER_PORT: "5432"
    ports:
      - "8083:8083"
    networks:
      - backend
networks:
  backend: 

