spring:
    application:
      name: execution-service 
    config:
      import: optional:configserver:http://config-server:8071
    main:
      banner-mode: console

---
spring:
  config:
    activate:
      on-profile: dev
  banner:
    location: classpath:banner-dev.txt

---
spring:
  config:
    activate:
      on-profile: prod
  banner:
    location: classpath:banner-prod.txt